config/routes.rb
Rails.application.routes.draw do
  get 'pages/index'
  get 'pages/new'
  post 'pages/create'
  get 'pages/:id/created', to: 'pages#created', as: 'pages_created'
  get 'pages/:id/edit', to: 'pages#edit', as: 'pages_edit'
  post 'pages/preview', to: 'pages#preview', as: 'pages_preview'
  patch 'pages/:id/update', to: 'pages#update', as: 'pages_update'
  delete 'pages/:id/delete', to: 'pages#destroy', as: 'pages_destroy'
  get 'pages/:id/show_confirmation_modal_for_delete', to: 'pages#show_confirmation_modal_for_delete', as: 'pages_show_confirmation_modal_for_delete'

  devise_for :users
  get 'public/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "public#index"
end

app/views/pages/_confirmation_modal_for_delete.html.erb
<div id="modal_inner" tabindex="-1" class="flex items-center justify-center overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 md:inset-0 h-modal md:h-full">
  <div class="fixed top-0 right-0 left-0 z-40 h-screen w-screen" style="background-color: rgba(51, 65, 85, 0.5);" onclick="this.closest('#modal_inner').remove()"></div>
  <div class="relative p-4 w-full max-w-lg h-full md:h-auto z-50">
    <div class="relative bg-white rounded-lg shadow">
      <button type="button" onclick="this.closest('#modal_inner').remove()" class="absolute top-2 right-2.5 text-slate-400 bg-transparent hover:bg-slate-200 hover:text-slate-900 rounded-lg text-sm p-2 ml-auto inline-flex items-center" data-modal-toggle="popup-modal">
        <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
      </button>
      <div class="p-6 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="mx-auto h-8 w-8 mb-4 text-slate-600" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
          <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
        </svg>
        <h3 class="mb-8 text-lg font-normal text-slate-500">Are you sure you want to delete this page named "<%= @page.name %>"? <span class="font-semibold">This action cannot be undone.</span></h3>
        <%= link_to 'Delete', pages_destroy_path(@page.id), data: { turbo_method: :delete }, class: "w-max h-max text-white bg-red-600 cursor-pointer border-2 border-transparent text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-red-600 focus:text-white focus:bg-red-600 mr-4" %>
        <a role="button" onclick="this.closest('#modal_inner').remove()" class="w-max h-max text-slate-500 bg-white cursor-pointer border-2 border-slate-500 text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-slate-300 outline-none focus:text-white focus:bg-slate-300">Cancel</a>
      </div>
    </div>
  </div>
</div>

app/views/pages/_preview_modal.html.erb
<%= turbo_frame_tag :preview_modal do %>
  <div id="preview_modal_inner" tabindex="-1" class="flex items-center justify-center overflow-y-auto overflow-x-hidden fixed top-0 right-0 left-0 md:inset-0 h-modal md:h-full">
    <div class="fixed top-0 right-0 left-0 z-40 h-screen w-screen" style="background-color: rgba(51, 65, 85, 0.5);" onclick="this.closest('#preview_modal_inner').remove()"></div>
    <div class="relative p-4 w-full max-w-full h-full md:h-auto z-50">
      <div class="relative bg-white rounded-lg shadow">
        <button type="button" onclick="this.closest('#preview_modal_inner').remove()" class="absolute top-2 right-2.5 text-slate-400 bg-transparent hover:bg-slate-200 hover:text-slate-900 rounded-lg text-sm p-2 ml-auto inline-flex items-center" data-modal-toggle="popup-modal">
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </button>
      </div>
      <div>
        <%= raw(html_content) %>
      </div>
    </div>
  </div>
<% end %>

app/views/pages/created.html.erb
<div class="mx-auto mt-8">
  <h1 class="mb-12 text-4xl font-bold text-slate-700 text-center">🎉 Success! Your page was created </h1>
  <%= link_to @page.path, class: "block mx-auto mb-16 w-max h-max text-white bg-liberty cursor-pointer border-2 border-transparent text-lg font-medium px-6 py-3 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-liberty focus:text-white focus:bg-liberty" do %>
    Visit my page at <span class="font-semibold underline"><%= @page.url %></span>
  <% end %>

  <p class="text-center text-sm font-medium text-slate-500 mb-4">As a next step, you can also...</p>
  <div class="flex max-w-3xl">
    <%= link_to 'See all my pages', pages_index_path, class: "w-1/3 block text-center underline text-lg text-slate-500 font-normal" %>
    <%= link_to 'Create another page', pages_new_path, class: "w-1/3 block text-center underline text-lg text-slate-500 font-normal" %>
    <%= link_to 'Edit this page', pages_edit_path(@page.id), class: "w-1/3 block text-center underline text-lg text-slate-500 font-normal" %>
  </div>
</div>

app/views/pages/edit.html.erb
<%= form_with url: pages_update_path(@page.id) do |form| %>
  <div class="w-full flex items-end mb-4">
    <div class="w-full">
      <%= form.label :page_name, "Page name (#{ENV['ROOT_URL']}/#{@page.name})", class: "block text-sm font-medium text-slate-500 mb-2" %>
      <%= form.text_field :page_name, placeholder: 'My_page_name', value: @page.name, class: 'flex-grow placeholder:text-slate-400 text-lg shadow appearance-none border border-slate-300 rounded-lg w-full px-4 py-2 text-slate-700 focus:outline-none focus:border-liberty-500' %>
    </div>
    <%= form.submit "Preview", formaction: pages_preview_path, formtarget: :_blank, formmethod: 'post', data: { turbo: false }, class: 'ml-4 flex-none w-max h-max text-slate-500 bg-white cursor-pointer border-2 border-slate-400 text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-slate-400 focus:text-white focus:bg-slate-400' %>
    <%= form.submit "Update", formmethod: 'patch', class: 'ml-4 flex-none w-max h-max text-white bg-liberty cursor-pointer border-2 border-transparent text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-liberty focus:text-white focus:bg-liberty' %>
  </div>

  <div class="w-full mb-10" data-controller="code-editor">
    <div data-code-editor-target="editor"></div>
  </div>

  <%= form.text_area :page_html, value: @page_html, class: 'hidden' %>
<% end %>

<%= turbo_frame_tag :preview_modal %>

app/views/pages/index.html.erb
<div class="mt-4">

  <div class="w-full mb-4 flex items-end justify-between">
    <h1 class="block font-bold text-slate-500 text-xl float-left">My pages</h1>
    <% if @pages.any? %>
      <%= link_to 'New page', pages_new_path, disabled: true, class: "w-max h-max text-white bg-liberty cursor-pointer border-2 border-transparent text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-liberty focus:text-white focus:bg-liberty" %>
    <% end %>
  </div>




  <table class="mb-8 shadow-xl table-fixed w-full border-collapse">
    <thead class="font-medium text-base bg-slate-200">
    <tr>
      <td class="rounded-tl-lg border-b border-slate-200 px-4 py-2">Page name</td>
      <td class="border-b border-slate-200 px-4 py-2">Size</td>
      <td class="hidden md:table-cell border-b border-slate-200 px-4 py-2">Created</td>
      <td class="hidden sm:table-cell border-b border-slate-200 px-4 py-2">Updated</td>
      <td class="rounded-tr-lg border-b border-slate-200 px-4 py-2"></td>
    </tr>
    </thead>
    <tbody class="text-lg">
    <% if @pages.any? %>
      <% @pages.each do |page| %>
      <tr id="<%= dom_id(page) %>">
        <td class="border-b border-slate-200 p-4">
          <%= link_to page.name, page.path, target: :_blank, data: { turbo: false }, class: "font-semibold underline hover:text-slate-500" %>
        </td>
        <td class="border-b border-slate-200 p-4 text-slate-700"><%= number_to_human_size(page.size) %></td>
        <td class="hidden md:table-cell border-b border-slate-200 p-4 text-slate-700"><%= time_ago_in_words(page.created_at) %> ago</td>
        <td class="hidden sm:table-cell border-b border-slate-200 p-4 text-slate-700"><%= time_ago_in_words(page.updated_at) %> ago</td>
        <td class="border-b border-slate-200 p-4 ml-auto">
          <div class="flex items-center justify-end">
            <%= link_to pages_edit_path(page.id), class: 'text-slate-400 hover:text-slate-500 font-medium flex justify-center items-center mr-12' do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
                <path stroke-linecap="round" stroke-linejoin="round" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z" />
              </svg>
              <span class="underline">Edit</span>
            <% end %>
            <%= link_to pages_show_confirmation_modal_for_delete_path(page.id), data: { turbo_frame: :modal }, class: 'text-red-200 hover:text-red-500 font-medium flex justify-center items-center' do %>
              <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                <path stroke-linecap="round" stroke-linejoin="round" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
              </svg>
            <% end %>
          </div>
        </td>
      </tr>
      <% end %>
    <% else %>
      <tr>
        <td rowspan="6" colspan="5" class="h-40">
          <div class="flex justify-center items-center">
            <%= link_to 'Create a new page', pages_new_path, class: "w-max h-max text-white bg-liberty cursor-pointer border-2 border-transparent text-lg font-semibold px-4 py-2 mr-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-liberty focus:text-white focus:bg-liberty" %>
          </div>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/pages/new.html.erb
<%= form_with url: pages_create_path, method: :post do |form| %>
  <div class="w-full flex items-end mb-4">
    <div class="w-full">
      <%= form.label :page_name, "Page name (#{ENV['ROOT_URL']}/My_Page_Name)", class: "block text-sm font-medium text-slate-500 mb-2" %>
      <%= form.text_field :page_name, placeholder: 'My_page_name', value: @page.name, class: 'flex-grow placeholder:text-slate-400 text-lg shadow appearance-none border border-slate-300 rounded-lg w-full px-4 py-2 text-slate-700 focus:outline-none focus:border-liberty-500' %>
    </div>
    <%= form.submit "Preview", formaction: pages_preview_path, formtarget: :_blank, data: { turbo: false }, class: 'ml-4 flex-none w-max h-max text-slate-500 bg-white cursor-pointer border-2 border-slate-400 text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-slate-400 focus:text-white focus:bg-slate-400' %>
    <%= form.submit "Create", class: 'ml-4 flex-none w-max h-max text-white bg-liberty cursor-pointer border-2 border-transparent text-lg font-semibold px-4 py-2 rounded-lg hover:shadow-xl hover:ring-offset-2 hover:ring hover:ring-liberty focus:text-white focus:bg-liberty' %>
  </div>

  <div class="w-full mb-10" data-controller="code-editor">
    <div data-code-editor-target="editor"></div>
  </div>

  <%= form.text_area :page_html, value: @page_html, class: 'hidden' %>
<% end %>